Refactor test framework

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -5,9 +5,11 @@ function run_test()
 {
     local test_name="$1"
 
-    echo "Running test $test_name"
+    log_dir="$log_base_dir/$(basename "$testsuite")/$(basename "$test_name")"
+    mkdir -p "$log_dir"
+    echo "  Running test $test_name"
     (
-        source "$test_name"
+        source "$test_dir/$test_name"
         cd "$test_dir"
         set +e
         (
@@ -18,32 +20,55 @@ function run_test()
         result=$?
         test_cleanup && exit $result
         exit $?
-    )
+    ) 2>"$log_dir/stderr.log" >"$log_dir/stdout.log"
     result=$?
     if [ $result -eq 0 ]; then
-        echo -e '  \e[0;32mTest successful.\e[0m'
+        echo -e '    \e[0;32mTest successful.\e[0m'
     else
-        echo -e '  \e[0;31mTest failed.\e[0m'
+        echo -e '    \e[0;31mTest failed.\e[0m'
     fi
     return $result
 }
 
+function full_path()
+{
+    cd "$(dirname "$1")"
+    echo "$PWD/$(basename "$1")"
+}
+
 set -e
 
-test_dir="$(dirname "$0")"
-cp -f "$1" "$test_dir/pipefs"
-shift
+binary_name="$(full_path "$1")"
+test_file="$(full_path "$2")"
+
+if [ ! -x "$binary_name" ]; then
+    echo "Invalid binary: $binary_name" >&2
+    exit 1
+fi
+if [ ! -e "$test_file" ]; then
+    echo "Invalid test file: $test_file" >&2
+    exit 1
+fi
+
+test_dir="$(full_path "$(dirname "$0")")"
+log_base_dir="$test_dir/logs/$(date '+%Y%m%d_%H%M%S%N')"
+
 source "$test_dir/test_fw.sh"
 source "$test_dir/test_common.sh"
+source "$test_file"
 
 fail_num=0
 run_num=0
-for test in "$@"; do
-    if ! run_test "$test"; then
-        (( ++fail_num ))
-    fi
+while read testsuite; do
+    source "$test_dir/$testsuite"
+    echo "Running test suite $(basename $testsuite)"
+    while read test; do
+        if ! run_test "$test"; then
+            (( ++fail_num ))
+        fi
+    done < <(get_test_cases)
     (( ++run_num ))
-done
+done < <(get_test_suites)
 
 echo "$fail_num out of $run_num failed."
 
